### PR TITLE
Moved to Ambient modules & XD 25 APIs

### LINKED ISSUE #67: 'SceneNode' refers to a value, but is being used as a type here ts(2749)
I'm getting this message after importing the new type defs directory (today Sept 28). 

> 'SceneNode' refers to a value, but is being used as a type here.ts(2749)

And this error: 

>Property 'SceneNode' does not exist on type 'typeof import("/Users/user/Library/Application Support/Adobe/Adobe XD/develop/myplugin/types/scenegraph")'.ts(2339)

It happens on the `const` line and the `@param` line:  

```
// there's a red underline under scene node
const {SceneNode} = require("scenegraph");

/**
 * Adds interaction
 * @param {SceneNode} item
 **/
function addInteractions(item, model) {

}
```

### LINKED ISSUE #71: XD 25: application.activeDocument
Create declarations for the new `application.activeDocument: DocumentInfo` and `typedef DocumentInfo` APIs. Cf. https://adobexdplatform.com/plugin-docs/reference/application.html#module_application-activeDocument

### PR DESCRIPTION
**Pull request by pklaschka**
### Contents of this Pull Request
This PR makes changes to
- [x] The typings in the `types` folder
- [x] Configuration files (`tsconfig.json`, `jsconfig.json`, `.gitignore` etc.)
- [x] The sample files (e.g., `sample.js`)
- [ ] The `README.md` or other files containing documentation
- [ ] Other

### Purpose of this Pull Request
Convert the definitions to ambient modules (which, as far as I understand it, is more correct) and make it more compatible for publishing to npm. 

### Issues resolved by this Pull Request
- fixes #67 (`Selection` renamed to `XDSelection` to avoid ambiguity with DOM types)
- fixes #71 

@ericdrobinson Would you mind taking a look at this? I've started to read a wonderful book about Typescript by Boris Cherny (I'm beginning to actually understand some of the deeper aspects of it, now) and it is my understanding that this is the actually correct way to do it (autocompletion works better than before, actually, and the config files appear more "clean" and correct, in my opinion).

### CODE REVIEW

File: types/scenegraph.d.ts [hunk 1]
```diff
@@ -1,1363 +1,1368 @@
...
+
+        /**
+         * Thickness in pixels of the stroke.
+         * value must be >= 0
+         */
+        strokeWidth: number;
+
+        /**
+         * @default `CENTER_STROKE` for most shapes, `INNER_STROKE` for Rectangle, Ellipse & Polygon
+         * Position of the stroke relative to the shape’s path outline: GraphicNode.INNER
```
Comment (ericdrobinson) [inline types/scenegraph.d.ts]: Is this line still required? Do things break if you remove it?

There is frustratingly little documentation about it, but I recall that it was required in order for the previous setup to work. It would be good to remove it now if it's become vestigial as it will help reduce confusion down the road...

**Review by ericdrobinson — COMMENTED** [review]
I've not taken a deep look at this (read: installed locally and poked around), but the changes overall look excellent.

File: types/scenegraph.d.ts (hunk 1 above)
Comment (pklaschka) [reply types/scenegraph.d.ts]: Sorry, to which line are you referring? The GitHub line comment stuff is a bit imprecise here, to say the least :slightly_smiling_face:

Comment (ericdrobinson) [reply types/scenegraph.d.ts]: Wow, yeah, this seems like a bug. If you actually look at this comment thread [in the review](https://github.com/AdobeXD/typings/pull/70/files/d4fe954cc257e283deb2dbc45d0fe24082ae58de#diff-cf67a8288b9d2067b7fc2fbf15ce9e43), it tags the _correct_ line. Specifically, it's this one:

```js
export {};
```

Comment (pklaschka) [reply types/scenegraph.d.ts]: Yes, it does unfortunately make a difference since without it, `RootNodeClass` and `SceneNodeClass` get exported as well...

Comment (pklaschka) [reply types/scenegraph.d.ts]: With the line in place:
image
Without the line:
image

(source: WebStorm 2019.3)

**Comment by pklaschka** [comment]
I'm going ahead and merging this now (since it also adds the new XD 25 APIs), we can, after all, still revert it if necessary (although I don't believe that that'll be needed)...
