### PR TITLE
Stop exporting SceneNode and RootNode

### LINKED ISSUE #56: `SceneNode` and `RootNode` not actually exported from `scenegraph`
From the looks of it, `SceneNode` and `RootNode` aren't actually exported classes in the `scenegraph` module. This is wrongly declared in the typings (`scenegraph.d.ts`).

### PR DESCRIPTION
**Pull request by pklaschka**
### Contents of this Pull Request
This PR makes changes to
- [x] The typings in the `types` folder
- [ ] Configuration files (`tsconfig.json`, `jsconfig.json`, `.gitignore` etc.)
- [ ] The sample files (e.g., `sample.js`)
- [ ] The `README.md` or other files containing documentation
- [ ] Other

### Purpose of this Pull Request
Solve the problem with falsely exported classes `SceneNode` and `RootNode` of the `scenegraph` module.

### Issues resolved by this Pull Request
- fixes #56

### CODE REVIEW

**Comment by pklaschka** [comment]
@ericdrobinson any thoughts? Does this work on your end?

**Comment by ericdrobinson** [comment]
@pklaschka It works but there is one major caveat: I think you were a little overzealous in replacing the class name throughout the file. The _**only**_ places that need the `[Type]Class` renaming are the actual class and subclass definitions. When you declare the interface for `SceneNode` and `RootNode`, you can continue to use those as types for constants, properties, return types, etc.

As the types exist in this PR at present, the `type` of `require('scenegraph').root` is `RootNodeClass`:
image

However, if you simply revert `root`'s type declaration to `export const root: RootNode;` then you get the following:
image

Mind replacing the _type annotations_ in `scenegraph.d.ts` with the `interface` versions of `RootNode` and `SceneNode` instead of the internally-named class versions?

**Comment by ericdrobinson** [comment]
@pklaschka Any movement on this? Perhaps a notification about the above comment slipped through the cracks?

**Comment by pklaschka** [comment]
I'm currently unable to update the repo as I'm in the middle of exams and don't have enough time. Until August 8th, I'll review (and possibly merge) pull requests, view comments, etc., but please understand that I don't have the time to actively update the repo for these next two weeks. Thank you very much for your understanding 🙂

**Comment by pklaschka** [comment]
@ericdrobinson I've found the time to fix that today (sorry it took so long, but it went right into my exams at university :sweat_smile:). If you have the time, could you perhaps look over it and see if it now works as expected? Thank you very much in advance.

Other than that, this is now a kind of mega PR also adding the new, panel-API `application.editDocument()` and fixes for a few other issues...

**Comment by ericdrobinson** [comment]
@pklaschka Awesome! Thanks for getting this done!

It seems that when you replaced the `SceneNodeClass` with `SceneNode` you didn't adjust the  definition of the sub-classes to `implement SceneNode` rather than `extends SceneNode`. Interfaces can extend classes but not the other way around.

Mind making the following adjustments?

```ts
// BEFORE:
export class GraphicNode extends SceneNode{
export class Group extends SceneNode{
export class SymbolInstance extends SceneNode{
export class RepeatGrid extends SceneNode{
export class LinkedGraphic extends SceneNode{
declare class RootNodeClass extends SceneNode{

// AFTER:
export class GraphicNode extends SceneNodeClass {
export class Group extends SceneNodeClass {
export class SymbolInstance extends SceneNodeClass {
export class RepeatGrid extends SceneNodeClass {
export class LinkedGraphic extends SceneNodeClass {
declare class RootNodeClass extends SceneNodeClass {
````

With the above adjustments, the class structure will work as expected.

I may have more suggestions. The above are the low-hanging fruit that VSCode reported as issues for me.

File: types/application.d.ts [hunk 1]
```diff
@@ -62,23 +62,23 @@ type RenditionSettings = {
     /**
      * (PNG & JPG renditions) DPI multipler in the range [0.1, 100], e.g. 2.0 for @2x DPI.
      */
-    scale: number;
+    scale?: number;
```
Comment (ericdrobinson) [inline types/application.d.ts]: This certainly works, but I think the user Issue #62 had the right idea here with the union `type` suggestion. It is entirely possible to help XD users initialize their data correctly using the type system.

The basic idea is that you create one `interface` for each Rendition Setting type that has a `type` that only accepts a _single possible string_: specifically one that aligns to one `RenditionType` `enum` option. Using `interface` extension, you can _also_ build the types such that you don't have to duplicate entries.

This is what I recommend:

```ts
interface RenditionSettingsBase
{
    /**
     * Root of scenegraph subtree to render. This may be any node in the scenegraph, regardless of the current edit context.
     */
    node: SceneNode;
    /**
     * File to save the rendition to (overwritten without warning if it already exists)
     */
    outputFile: storage.File;
}

interface RenditionSettingsPNGorJPG extends RenditionSettingsBase
{
    /**
     * (PNG & JPG renditions) DPI multipler in the range [0.1, 100], e.g. 2.0 for @2x DPI.
     */
    scale: number;
    /**
     * (PNG & JPEG renditions) Alpha component ignored for JPG. Optional: defaults to transparent for PNG, solid white for JPG.
     */
    background?: Color;
}

export interface RenditionSettingsPNG extends RenditionSettingsPNGorJPG
{
    /**
     * File type
     */
    type: RenditionType.PNG;
}

export interface RenditionSettingsJPG extends RenditionSettingsPNGorJPG
{
    /**
     * File type.
     */
    type: RenditionType.JPG;
    /**
     * (JPG renditions) Compression quality in the range [1, 100].
     */
    quality: number;
}

export interface RenditionSettingsSVG extends RenditionSettingsBase
{
    /**
     * File type.
     */
    type: RenditionType.SVG;
    /**
     * (SVG renditions) If true, SVG code is minified.
     */
    minify: boolean;
    /**
     * (SVG renditions) If true, bitmap images are stored as base64 data inside the SVG file. If false, bitmap images are saved as separate files linked from the SVG code.
     */
    embedImages: boolean;
}

export interface RenditionSettingsPDF extends RenditionSettingsBase
{
    /**
     * File type
     */
    type: RenditionType.PDF;
}

export type RenditionSettings = RenditionSettingsPNG | RenditionSettingsJPG | RenditionSettingsSVG | RenditionSettingsPDF;
```

I believe that the above structure captures the goal of the documentation:

>_All rendition settings fields are required_ (for a given rendition type) unless otherwise specified.

The point is that Adobe called out the applicable types in the descriptions rather than simply breaking these out into separate typedefs. With the actual type declarations, we can make  that documentation _actionable_.

**Comment by pklaschka** [comment]
@ericdrobinson That should all be fixed now, thanks again for your input :slightly_smiling_face: :+1:

**Comment by pklaschka** [comment]
Same procedure as every PR :wink: 

I'll wait for a few days (specifically, until Tuesday, 8:00 PM UTC), and if there are no objections until then, I'll go ahead and merge this, marking it as release 22.0 of the typings...
